name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - ruby-head
        rails:
          - '6.1'
          - '7.0'
          - '7.1'
    continue-on-error: ${{ matrix.ruby == 'ruby-head' }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake
